name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: alpine:3.20

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: apk add --no-cache build-base make

      - name: Run Makefile tests
        run: make test
